/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppMyScriptsRouteImport } from './routes/_app.my-scripts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOsmAllocationRouteImport } from './routes/_app.osm.allocation'
import { Route as AppMasterNameRouteImport } from './routes/_app.master.$name'
import { Route as AppEvaluateScriptIdRouteImport } from './routes/_app.evaluate.$scriptId'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppEvaluateScriptIdSummaryRouteImport } from './routes/_app.evaluate.$scriptId.summary'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMyScriptsRoute = AppMyScriptsRouteImport.update({
  id: '/my-scripts',
  path: '/my-scripts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOsmAllocationRoute = AppOsmAllocationRouteImport.update({
  id: '/osm/allocation',
  path: '/osm/allocation',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterNameRoute = AppMasterNameRouteImport.update({
  id: '/master/$name',
  path: '/master/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluateScriptIdRoute = AppEvaluateScriptIdRouteImport.update({
  id: '/evaluate/$scriptId',
  path: '/evaluate/$scriptId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluateScriptIdSummaryRoute =
  AppEvaluateScriptIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AppEvaluateScriptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-scripts': typeof AppMyScriptsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/evaluate/$scriptId': typeof AppEvaluateScriptIdRouteWithChildren
  '/master/$name': typeof AppMasterNameRoute
  '/osm/allocation': typeof AppOsmAllocationRoute
  '/evaluate/$scriptId/summary': typeof AppEvaluateScriptIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-scripts': typeof AppMyScriptsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/evaluate/$scriptId': typeof AppEvaluateScriptIdRouteWithChildren
  '/master/$name': typeof AppMasterNameRoute
  '/osm/allocation': typeof AppOsmAllocationRoute
  '/evaluate/$scriptId/summary': typeof AppEvaluateScriptIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-scripts': typeof AppMyScriptsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/evaluate/$scriptId': typeof AppEvaluateScriptIdRouteWithChildren
  '/_app/master/$name': typeof AppMasterNameRoute
  '/_app/osm/allocation': typeof AppOsmAllocationRoute
  '/_app/evaluate/$scriptId/summary': typeof AppEvaluateScriptIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/my-scripts'
    | '/reports'
    | '/results'
    | '/admin/users'
    | '/evaluate/$scriptId'
    | '/master/$name'
    | '/osm/allocation'
    | '/evaluate/$scriptId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/my-scripts'
    | '/reports'
    | '/results'
    | '/admin/users'
    | '/evaluate/$scriptId'
    | '/master/$name'
    | '/osm/allocation'
    | '/evaluate/$scriptId/summary'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/my-scripts'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/admin/users'
    | '/_app/evaluate/$scriptId'
    | '/_app/master/$name'
    | '/_app/osm/allocation'
    | '/_app/evaluate/$scriptId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-scripts': {
      id: '/_app/my-scripts'
      path: '/my-scripts'
      fullPath: '/my-scripts'
      preLoaderRoute: typeof AppMyScriptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/osm/allocation': {
      id: '/_app/osm/allocation'
      path: '/osm/allocation'
      fullPath: '/osm/allocation'
      preLoaderRoute: typeof AppOsmAllocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master/$name': {
      id: '/_app/master/$name'
      path: '/master/$name'
      fullPath: '/master/$name'
      preLoaderRoute: typeof AppMasterNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluate/$scriptId': {
      id: '/_app/evaluate/$scriptId'
      path: '/evaluate/$scriptId'
      fullPath: '/evaluate/$scriptId'
      preLoaderRoute: typeof AppEvaluateScriptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluate/$scriptId/summary': {
      id: '/_app/evaluate/$scriptId/summary'
      path: '/summary'
      fullPath: '/evaluate/$scriptId/summary'
      preLoaderRoute: typeof AppEvaluateScriptIdSummaryRouteImport
      parentRoute: typeof AppEvaluateScriptIdRoute
    }
  }
}

interface AppEvaluateScriptIdRouteChildren {
  AppEvaluateScriptIdSummaryRoute: typeof AppEvaluateScriptIdSummaryRoute
}

const AppEvaluateScriptIdRouteChildren: AppEvaluateScriptIdRouteChildren = {
  AppEvaluateScriptIdSummaryRoute: AppEvaluateScriptIdSummaryRoute,
}

const AppEvaluateScriptIdRouteWithChildren =
  AppEvaluateScriptIdRoute._addFileChildren(AppEvaluateScriptIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyScriptsRoute: typeof AppMyScriptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEvaluateScriptIdRoute: typeof AppEvaluateScriptIdRouteWithChildren
  AppMasterNameRoute: typeof AppMasterNameRoute
  AppOsmAllocationRoute: typeof AppOsmAllocationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMyScriptsRoute: AppMyScriptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEvaluateScriptIdRoute: AppEvaluateScriptIdRouteWithChildren,
  AppMasterNameRoute: AppMasterNameRoute,
  AppOsmAllocationRoute: AppOsmAllocationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
